// This file was generated by `crates/server/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Project = { id: string, name: string, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, git_no_verify_override: boolean | null, scheduler_max_concurrent: number, scheduler_max_retries: number, default_continuation_turns: number, mcp_auto_executor_policy_mode: ProjectMcpExecutorPolicyMode, mcp_auto_executor_policy_allow_list: Array<ProjectExecutorProfileAllowListEntry>, after_prepare_hook: WorkspaceLifecycleHookConfig | null, before_cleanup_hook: WorkspaceLifecycleHookConfig | null, remote_project_id: string | null, created_at: Date, updated_at: Date, };

export type ProjectPublic = { id: string, name: string, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, git_no_verify_override: boolean | null, scheduler_max_concurrent: number, scheduler_max_retries: number, default_continuation_turns: number, mcp_auto_executor_policy_mode: ProjectMcpExecutorPolicyMode, mcp_auto_executor_policy_allow_list: Array<ProjectExecutorProfileAllowListEntry>, after_prepare_hook: WorkspaceLifecycleHookConfig | null, before_cleanup_hook: WorkspaceLifecycleHookConfig | null, remote_project_id: string | null, };

export type WorkspaceLifecycleHookConfig = { command: string, working_dir: string | null, failure_policy: WorkspaceLifecycleHookFailurePolicy, run_mode: WorkspaceLifecycleHookRunMode | null, };

export type ProjectMcpExecutorPolicyMode = "inherit_all" | "allow_list";

export type ProjectExecutorProfileAllowListEntry = { executor: string, variant: string | null, };

export type WorkspaceLifecycleHookFailurePolicy = "block_start" | "warn_only" | "block_cleanup";

export type WorkspaceLifecycleHookRunMode = "once_per_workspace" | "every_prepare";

export type WorkspaceLifecycleHookPhase = "after_prepare" | "before_cleanup";

export type WorkspaceLifecycleHookStatus = "succeeded" | "failed";

export type CreateProject = { name: string, repositories: Array<CreateProjectRepo>, };

export type UpdateProject = { name: string | null, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, git_no_verify_override: boolean | null | null, scheduler_max_concurrent: number | null, scheduler_max_retries: number | null, default_continuation_turns: number | null, after_prepare_hook: WorkspaceLifecycleHookConfig | null | null, before_cleanup_hook: WorkspaceLifecycleHookConfig | null | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };

export type ProjectFileSearchResponse = { results: Array<SearchResult>, index_truncated: boolean, truncated_repos: Array<string>, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type Repo = { id: string, path: string, name: string, display_name: string, created_at: Date, updated_at: Date, };

export type ProjectRepo = { id: string, project_id: string, repo_id: string, setup_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean, };

export type ProjectRepoPublic = { id: string, project_id: string, repo_id: string, has_setup_script: boolean, has_cleanup_script: boolean, has_copy_files: boolean, parallel_setup_script: boolean, };

export type CreateProjectRepo = { display_name: string, git_repo_path: string, };

export type UpdateProjectRepo = { setup_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean | null, };

export type WorkspaceRepo = { id: string, workspace_id: string, repo_id: string, target_branch: string, created_at: Date, updated_at: Date, };

export type CreateWorkspaceRepo = { repo_id: string, target_branch: string, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type TaskKind = "default" | "milestone";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, task_kind: TaskKind, milestone_id: string | null, milestone_node_id: string | null, parent_workspace_id: string | null, origin_task_id: string | null, created_by_kind: TaskCreatedByKind, 
/**
 * NULL = inherit project default continuation budget.
 */
continuation_turns_override: number | null, shared_task_id: string | null, archived_kanban_id: string | null, created_at: string, updated_at: string, };

export type TaskCreatedByKind = "human_ui" | "mcp" | "scheduler" | "agent_followup" | "milestone_planner";

export type VkNextAction = "continue" | "review";

export type TaskContinuationStopReasonCode = "disabled" | "budget_exhausted" | "approval_pending" | "vk_next_review" | "vk_next_missing" | "vk_next_invalid" | "human_queued_follow_up" | "task_not_actionable" | "start_failed";

export type TaskControlTransferReasonCode = "human_takeover" | "human_resume" | "awaiting_human_review" | "policy_rejected_profile";

export type TaskContinuationBudgetSource = "project_default" | "task_override";

export type TaskContinuationStopReason = { code: TaskContinuationStopReasonCode, detail: string | null, at: Date, };

export type TaskContinuationDiagnostics = { turns_used: number, turn_budget: number, turns_remaining: number, budget_source: TaskContinuationBudgetSource, last_vk_next_action: VkNextAction | null, last_vk_next_at: Date | null, stop_reason: TaskContinuationStopReason | null, };

export type TaskControlTransferDiagnostics = { reason_code: TaskControlTransferReasonCode, detail: string | null, at: Date, };

export type TaskOrchestrationDiagnostics = { continuation: TaskContinuationDiagnostics, last_control_transfer: TaskControlTransferDiagnostics | null, };

export type TaskWithAttemptStatus = { has_in_progress_attempt: boolean, last_attempt_failed: boolean, executor: string, dispatch_state: TaskDispatchState | null, orchestration: TaskOrchestrationDiagnostics | null, id: string, project_id: string, title: string, description: string | null, status: TaskStatus, task_kind: TaskKind, milestone_id: string | null, milestone_node_id: string | null, parent_workspace_id: string | null, origin_task_id: string | null, created_by_kind: TaskCreatedByKind, 
/**
 * NULL = inherit project default continuation budget.
 */
continuation_turns_override: number | null, shared_task_id: string | null, archived_kanban_id: string | null, created_at: string, updated_at: string, };

export type TaskDispatchState = { task_id: string, controller: TaskDispatchController, status: TaskDispatchStatus, retry_count: number, max_retries: number, last_error: string | null, blocked_reason: string | null, next_retry_at: Date | null, claim_expires_at: Date | null, created_at: Date, updated_at: Date, };

export type TaskDispatchController = "manual" | "scheduler";

export type TaskDispatchStatus = "idle" | "claimed" | "running" | "retry_scheduled" | "awaiting_human_review" | "blocked";

export type ArchivedKanban = { id: string, project_id: string, title: string, created_at: string, updated_at: string, };

export type ArchivedKanbanWithTaskCount = { tasks_count: bigint, id: string, project_id: string, title: string, created_at: string, updated_at: string, };

export type TaskRelationships = { parent_task: Task | null, current_workspace: Workspace, children: Array<Task>, };

export type TaskLineageSummary = { origin_task: Task | null, follow_up_tasks: Array<Task>, };

export type CreateTask = { project_id: string, title: string, description: string | null, status: TaskStatus | null, task_kind: TaskKind | null, milestone_id: string | null, milestone_node_id: string | null, parent_workspace_id: string | null, origin_task_id: string | null, created_by_kind: TaskCreatedByKind | null, image_ids: Array<string> | null, shared_task_id: string | null, };

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, parent_workspace_id: string | null, image_ids: Array<string> | null, continuation_turns_override: number | null | null, };

export type Milestone = { id: string, project_id: string, title: string, description: string | null, objective: string | null, definition_of_done: string | null, default_executor_profile_id: ExecutorProfileId | null, automation_mode: MilestoneAutomationMode, run_next_step_requested_at: string | null, status: TaskStatus, baseline_ref: string, schema_version: number, graph: MilestoneGraph, suggested_status: TaskStatus, last_plan_application: MilestonePlanApplicationSummary | null, created_at: string, updated_at: string, };

export type MilestonePlanApplicationSummary = { id: string, milestone_id: string, schema_version: number, applied_by_kind: TaskCreatedByKind, idempotency_key: string | null, applied_at: string, };

export type CreateMilestone = { project_id: string, title: string, description: string | null, objective: string | null, definition_of_done: string | null, default_executor_profile_id: ExecutorProfileId | null, automation_mode: MilestoneAutomationMode | null, status: TaskStatus | null, baseline_ref: string | null, schema_version: number, graph: MilestoneGraph, };

export type UpdateMilestone = { title: string | null, description: string | null, objective: string | null, definition_of_done: string | null, default_executor_profile_id: ExecutorProfileId | null | null, automation_mode: MilestoneAutomationMode | null, status: TaskStatus | null, baseline_ref: string | null, schema_version: number | null, graph: MilestoneGraph | null, };

export type MilestoneAutomationMode = "manual" | "auto";

export type RunNextMilestoneStepStatus = "queued" | "queued_waiting_for_active_attempt" | "not_eligible";

export type RunNextMilestoneStepResponse = { status: RunNextMilestoneStepStatus, requested_at: string | null, candidate_task_id: string | null, message: string | null, };

export type PushMilestoneBaselineRequest = { force: boolean, };

export type PushMilestoneBaselineStatus = "pushed" | "force_push_required" | "skipped_no_remote" | "failed";

export type PushMilestoneBaselineRepoResult = { repo_id: string, repo_display_name: string, status: PushMilestoneBaselineStatus, message: string | null, };

export type PushMilestoneBaselineResponse = { branch: string, results: Array<PushMilestoneBaselineRepoResult>, };

export type MilestoneGraph = { nodes: Array<MilestoneNode>, edges: Array<MilestoneEdge>, };

export type MilestoneNode = { id: string, task_id: string, kind: MilestoneNodeKind, phase: number, executor_profile_id: ExecutorProfileId | null, base_strategy: MilestoneNodeBaseStrategy, instructions: string | null, requires_approval: boolean | null, layout: MilestoneNodeLayout, status?: TaskStatus | null, };

export type MilestoneNodeLayout = { x: number, y: number, };

export enum MilestoneNodeKind { task = "task", checkpoint = "checkpoint", merge = "merge" }

export enum MilestoneNodeBaseStrategy { topology = "topology", baseline = "baseline" }

export type MilestoneEdge = { id: string, from: string, to: string, data_flow: string | null, };

export type MilestonePlanV1 = { schema_version: number, milestone: MilestonePlanMilestonePatchV1, nodes: Array<MilestonePlanNodeV1>, edges: Array<MilestonePlanEdgeV1>, };

export type MilestonePlanMilestonePatchV1 = { objective: string | null, definition_of_done: string | null, 
/**
 * Mirrors `UpdateMilestone.default_executor_profile_id` semantics:
 * - None: no change
 * - Some(Some(id)): set
 * - Some(None): clear
 */
default_executor_profile_id: ExecutorProfileId | null | null, automation_mode: MilestoneAutomationMode | null, baseline_ref: string | null, };

export type MilestonePlanCreateTaskV1 = { title: string, description: string | null, };

export type MilestonePlanNodeV1 = { id: string, kind: MilestoneNodeKind, phase: number, executor_profile_id: ExecutorProfileId | null, base_strategy: MilestoneNodeBaseStrategy, instructions: string | null, requires_approval: boolean | null, layout: MilestoneNodeLayout | null, task_id: string | null, create_task: MilestonePlanCreateTaskV1 | null, };

export type MilestonePlanEdgeV1 = { from: string, to: string, data_flow: string | null, };

export type MilestonePlanMetadataField = "objective" | "definition_of_done" | "default_executor_profile" | "automation_mode" | "baseline_ref";

export type MilestonePlanPreviewMetadataChange = { field: MilestonePlanMetadataField, from: string | null, to: string | null, };

export type MilestonePlanPreviewTaskToCreate = { node_id: string, title: string, description: string | null, };

export type MilestonePlanPreviewTaskLink = { node_id: string, task_id: string, };

export type MilestonePlanEdgeKeyV1 = { from: string, to: string, data_flow: string | null, };

export type MilestonePlanPreviewNodeDiff = { existing: Array<string>, planned: Array<string>, added: Array<string>, removed: Array<string>, };

export type MilestonePlanPreviewEdgeDiff = { existing: Array<MilestonePlanEdgeKeyV1>, planned: Array<MilestonePlanEdgeKeyV1>, added: Array<MilestonePlanEdgeKeyV1>, removed: Array<MilestonePlanEdgeKeyV1>, };

export type MilestonePlanPreviewResponse = { metadata_changes: Array<MilestonePlanPreviewMetadataChange>, tasks_to_create: Array<MilestonePlanPreviewTaskToCreate>, task_links: Array<MilestonePlanPreviewTaskLink>, node_diff: MilestonePlanPreviewNodeDiff, edge_diff: MilestonePlanPreviewEdgeDiff, };

export type MilestonePlanApplyResponse = { milestone: Milestone, created_tasks: Array<Task>, applied_at: string, };

export type MilestonePlanExtractionKind = "fenced" | "embedded";

export type MilestonePlanDetectionStatus = "found" | "not_found" | "invalid" | "unsupported";

export type MilestonePlanDetectionResult = { status: MilestonePlanDetectionStatus, plan: MilestonePlanV1 | null, extracted_from: MilestonePlanExtractionKind | null, source_turn_id: string | null, source_entry_index: number | null, error: string | null, };

export type DraftFollowUpData = { message: string, variant: string | null, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type Image = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type CreateImage = { file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, };

export type Workspace = { id: string, task_id: string, container_ref: string | null, branch: string, agent_working_dir: string | null, setup_completed_at: string | null, latest_hook_run: WorkspaceLifecycleHookRunSummary | null, after_prepare_hook_status: WorkspaceLifecycleHookStatus | null, after_prepare_hook_ran_at: Date | null, after_prepare_hook_error_summary: string | null, before_cleanup_hook_status: WorkspaceLifecycleHookStatus | null, before_cleanup_hook_ran_at: Date | null, before_cleanup_hook_error_summary: string | null, created_at: string, updated_at: string, };

export type WorkspaceLifecycleHookRunSummary = { phase: WorkspaceLifecycleHookPhase, status: WorkspaceLifecycleHookStatus, ran_at: Date, error_summary: string | null, };

export type Session = { id: string, workspace_id: string, executor: string | null, created_at: string, updated_at: string, };

export type ExecutionProcessPublic = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: bigint | null, dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "codingagent" | "devserver";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type CreateApprovalRequest = { tool_name: string, tool_input: JsonValue, tool_call_id: string, };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalStatus, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type DiffSummary = { fileCount: number, added: number, deleted: number, totalBytes: number, };

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type RegisterRepoRequest = { path: string, display_name: string | null, };

export type InitRepoRequest = { parent_path: string, folder_name: string, };

export type TagSearchParams = { search: string | null, };

export type UserSystemInfo = { config: Config, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, 
/**
 * Resolved command source/version per executor
 */
agent_command_resolutions: { [key in string]?: AgentCommandResolution }, executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type ConfigStatusResponse = { config_dir: string, config_path: string, projects_path: string, projects_dir: string, secret_env_path: string, schema_path: string, projects_schema_path: string, loaded_at_unix_ms: number, last_error: string | null, dirty: boolean, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type CheckAgentCompatibilityQuery = { executor: BaseCodingAgent, variant: string | null, refresh: boolean | null, };

export type CliDependencyPreflightQuery = { executor: BaseCodingAgent, };

export type CliDependencyPreflightResponse = { agent: AvailabilityInfo, };

export type ImportLlmanProfilesResponse = { path: string, imported: number, updated: number, skipped: number, };

export type ResolveLlmanPathResponse = { path: string | null, };

export type CreateFollowUpAttempt = { prompt: string, variant: string | null, retry_process_id: string | null, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ChangeTargetBranchRequest = { repo_id: string, new_target_branch: string, };

export type ChangeTargetBranchResponse = { repo_id: string, new_target_branch: string, status: [number, number], };

export type MergeTaskAttemptRequest = { repo_id: string, };

export type PushTaskAttemptRequest = { repo_id: string, };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type AttemptState = "idle" | "running" | "completed" | "failed";

export type TaskAttemptStatusResponse = { attempt_id: string, task_id: string, workspace_branch: string, created_at: string, updated_at: string, latest_session_id: string | null, latest_execution_process_id: string | null, state: AttemptState, last_activity_at: string | null, failure_summary: string | null, };

export type CreateAndStartTaskRequest = { task: CreateTask, executor_profile_id: ExecutorProfileId, repos: Array<WorkspaceRepoInput>, };

export type ArchiveProjectKanbanRequest = { statuses: Array<TaskStatus>, title: string | null, };

export type ArchiveProjectKanbanResponse = { archived_kanban: ArchivedKanbanWithTaskCount, moved_task_count: bigint, };

export type GetArchivedKanbanResponse = { archived_kanban: ArchivedKanbanWithTaskCount, };

export type RestoreArchivedKanbanRequest = { restore_all: boolean | null, statuses: Array<TaskStatus> | null, };

export type RestoreArchivedKanbanResponse = { restored_task_count: bigint, };

export type DeleteArchivedKanbanResponse = { deleted_task_count: bigint, };

export type ImageResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type ImageMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type IndexedLogEntry = { entry_index: bigint, entry: PatchType, };

export type LogHistoryPage = { entries: Array<IndexedLogEntry>, next_cursor: bigint | null, has_more: boolean, history_truncated: boolean, };

export type LogStreamEvent = { "type": "append", entry_index: bigint, entry: PatchType, } | { "type": "replace", entry_index: bigint, entry: PatchType, } | { "type": "finished" };

export type CreateTaskAttemptBody = { task_id: string, executor_profile_id: ExecutorProfileId, repos: Array<WorkspaceRepoInput>, prompt_preset: TaskAttemptPromptPreset | null, };

export type TaskAttemptPromptPreset = "milestone_planning";

export type WorkspaceRepoInput = { repo_id: string, target_branch: string, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type RebaseTaskAttemptRequest = { repo_id: string, old_base_branch: string | null, new_base_branch: string | null, };

export type AbortConflictsRequest = { repo_id: string, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type BranchStatus = { commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type RunScriptError = { "type": "no_script_configured" } | { "type": "process_already_running" };

export type RepoBranchStatus = { repo_id: string, repo_name: string, commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type ProjectRepoConfig = { path: string, display_name: string | null, setup_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean, };

export type ProjectConfig = { id: string | null, remote_project_id: string | null, name: string, repos: Array<ProjectRepoConfig>, dev_script: string | null, dev_script_working_dir: string | null, default_agent_working_dir: string | null, git_no_verify_override: boolean | null, scheduler_max_concurrent: number, scheduler_max_retries: number, default_continuation_turns: number, mcp_auto_executor_policy_mode: ProjectMcpExecutorPolicyMode, mcp_auto_executor_policy_allow_list: Array<ExecutorProfileId>, after_prepare_hook: WorkspaceLifecycleHookConfig | null, before_cleanup_hook: WorkspaceLifecycleHookConfig | null, };

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, executor_profiles: ExecutorConfigs | null, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, git_no_verify: boolean, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, llman_claude_code_path: string | null, diff_preview_guard: DiffPreviewGuardPreset, access_control: AccessControlConfig, projects: Array<ProjectConfig>, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, };

export enum EditorType { NONE = "NONE", VS_CODE = "VS_CODE", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "editor_integration_disabled" } | { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "ZH_HANS";

export type ShowcaseState = { seen_features: Array<string>, };

export enum DiffPreviewGuardPreset { SAFE = "SAFE", BALANCED = "BALANCED", RELAXED = "RELAXED", OFF = "OFF" }

export enum AccessControlMode { DISABLED = "DISABLED", TOKEN = "TOKEN" }

export type AccessControlConfig = { mode: AccessControlMode, token: string | null, allow_localhost_bypass: boolean, };

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest;

export type ScriptContext = "SetupScript" | "CleanupScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, 
/**
 * Optional relative path to execute the script in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export type AgentCommandResolution = { source: AgentCommandSource, version?: string | null, status: AgentCommandStatus, fallback_to_latest: boolean, };

export enum AgentCommandSource { PNPM_GLOBAL = "PNPM_GLOBAL", NPM_GLOBAL = "NPM_GLOBAL", NPX_LATEST = "NPX_LATEST", SYSTEM_BINARY = "SYSTEM_BINARY", OVERRIDE = "OVERRIDE", UNKNOWN = "UNKNOWN" }

export enum AgentCommandStatus { CHECKING = "CHECKING", READY = "READY" }

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", FAKE_AGENT = "FAKE_AGENT", OPENCODE = "OPENCODE", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "CODEX": Codex };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorConfig = { [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "CODEX": Codex } };

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER" }

export type ClaudeCode = { append_prompt: AppendPrompt, auto_retry: AutoRetryConfig, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, auto_retry: AutoRetryConfig, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, enable_dynamic_tools?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CodexProtocolCompatibilityStatus = "compatible" | "incompatible" | "not_installed" | "unknown";

export type CodexProtocolCompatibility = { status: CodexProtocolCompatibilityStatus, expected_v2_schema_sha256: string, runtime_v2_schema_sha256: string | null, codex_cli_version: string | null, base_command: string, message: string | null, };

export type AutoRetryConfig = { error_patterns: Array<string>, delay_seconds: number, max_attempts: number, };

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, 
/**
 * Optional image path map keyed by prompt image src.
 */
image_paths?: { [key in string]?: string } | null, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, image_paths?: { [key in string]?: string } | null, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, metadata: JsonValue | null, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "other", description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, requested_at: string, timeout_at: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;