use std::{collections::HashMap, path::PathBuf};

use anyhow::{Context, Result};
use chrono::Utc;

use crate::migrate::{
    io::{atomic_write_out, atomic_write_out_secure, timestamp_slug},
    secrets::{
        config_json_to_yaml_fragment, profiles_json_to_executor_profiles_yaml,
        secret_env_to_string, validate_yaml_with_secret_env,
    },
};

#[derive(Debug, Default, Clone)]
pub struct ExportAssetConfigYamlArgs {
    pub out: Option<PathBuf>,
    pub install: bool,
    pub dry_run: bool,
    pub print_paths: bool,
    pub config_dir_override: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportAssetConfigYamlParseResult {
    Help,
    Run,
}

pub const EXPORT_ASSET_CONFIG_YAML_DEPRECATION_WARNING: &str = "DEPRECATED: asset_dir()/config.json and asset_dir()/profiles.json are legacy. This migration tool will be removed in a future release.";

pub fn export_asset_config_yaml_help() -> &'static str {
    r#"Export legacy asset config (config.json + profiles.json) into YAML config fields.

DEPRECATED:
  asset_dir()/config.json and asset_dir()/profiles.json are legacy. This migration tool will be removed in a future release.

Usage:
  export-asset-config-yaml --out <path>
  export-asset-config-yaml --out -
  export-asset-config-yaml --install
  export-asset-config-yaml --install --dry-run
  export-asset-config-yaml --print-paths

Notes:
  - Output is a YAML mapping containing selected fields from legacy `config.json` and `profiles.json`
  - Secrets are NOT written into YAML; they are written into `secret.env.migrated.<timestamp>` and referenced via `{{secret.NAME}}`
  - Only supported executors (default: CLAUDE_CODE + CODEX) are migrated from `profiles.json`
  - Output directory for --install is resolved the same way as VK:
    - Prefer `VK_CONFIG_DIR`
    - Otherwise OS config dir (~/.config/vk on Linux/macOS, %APPDATA%\\vk on Windows)
  - --install writes new files (config.migrated.<timestamp>.yaml + secret.env.migrated.<timestamp>) and does NOT overwrite config.yaml/secret.env
"#
}

pub fn parse_export_asset_config_yaml_args(
    args: impl IntoIterator<Item = String>,
) -> Result<(ExportAssetConfigYamlArgs, ExportAssetConfigYamlParseResult)> {
    let mut out = None;
    let mut install = false;
    let mut dry_run = false;
    let mut print_paths = false;

    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        if arg == "--out" {
            let value = args.next().context("Missing value for --out")?;
            let trimmed = value.trim();
            if trimmed.is_empty() {
                anyhow::bail!("--out must not be empty");
            }
            out = Some(PathBuf::from(trimmed));
            continue;
        }
        if arg == "--install" {
            install = true;
            continue;
        }
        if arg == "--dry-run" {
            dry_run = true;
            continue;
        }
        if arg == "--print-paths" {
            print_paths = true;
            continue;
        }
        if arg == "--help" || arg == "-h" {
            return Ok((
                ExportAssetConfigYamlArgs::default(),
                ExportAssetConfigYamlParseResult::Help,
            ));
        }

        anyhow::bail!("Unknown argument: {arg}");
    }

    if out.is_some() && install {
        anyhow::bail!("--out and --install are mutually exclusive");
    }

    Ok((
        ExportAssetConfigYamlArgs {
            out,
            install,
            dry_run,
            print_paths,
            config_dir_override: None,
        },
        ExportAssetConfigYamlParseResult::Run,
    ))
}

pub async fn run(args: Vec<String>) -> Result<()> {
    let (parsed, action) = parse_export_asset_config_yaml_args(args)?;
    if action == ExportAssetConfigYamlParseResult::Help {
        println!("{}", export_asset_config_yaml_help());
        return Ok(());
    }
    run_export_asset_config_yaml(parsed).await
}

fn build_config_yaml_file(contents_yaml: &str, tool_name: &str) -> String {
    let header = "# yaml-language-server: $schema=./config.schema.json\n";
    let generated = format!(
        "# Generated by {tool_name} at {}\n",
        Utc::now().to_rfc3339()
    );

    let mut out = String::new();
    out.push_str(header);
    out.push_str(&generated);
    out.push_str(contents_yaml);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

pub async fn run_export_asset_config_yaml(args: ExportAssetConfigYamlArgs) -> Result<()> {
    eprintln!("{EXPORT_ASSET_CONFIG_YAML_DEPRECATION_WARNING}");

    let config_dir = args
        .config_dir_override
        .clone()
        .unwrap_or_else(utils_core::vk_config_dir);
    let config_path = config_dir.join("config.yaml");
    let secret_env_path = config_dir.join("secret.env");

    let legacy_config_json = utils_assets::asset_dir().join("config.json");
    let legacy_profiles_json = utils_assets::asset_dir().join("profiles.json");

    if args.print_paths {
        println!("asset_dir: {}", utils_assets::asset_dir().display());
        println!("legacy_config_json: {}", legacy_config_json.display());
        println!("legacy_profiles_json: {}", legacy_profiles_json.display());
        println!("config_dir: {}", config_dir.display());
        println!("config_yaml: {}", config_path.display());
        println!("secret_env: {}", secret_env_path.display());
        return Ok(());
    }

    if !args.install && args.out.is_none() {
        anyhow::bail!("Missing output mode: use --out <path> or --install (see --help)");
    }

    let mut fragment = serde_yaml::Mapping::new();
    let mut secrets = HashMap::<String, String>::new();

    if legacy_config_json.exists() {
        let raw = std::fs::read_to_string(&legacy_config_json)
            .with_context(|| format!("Failed to read {}", legacy_config_json.display()))?;
        let value = serde_json::from_str::<serde_json::Value>(&raw)
            .with_context(|| format!("Failed to parse {}", legacy_config_json.display()))?;
        let cfg_fragment = config_json_to_yaml_fragment(value, &mut secrets)?;
        for (k, v) in cfg_fragment {
            fragment.insert(k, v);
        }
    } else {
        eprintln!(
            "warning: legacy config.json not found at {}, skipping",
            legacy_config_json.display()
        );
    }

    if legacy_profiles_json.exists() {
        let raw = std::fs::read_to_string(&legacy_profiles_json)
            .with_context(|| format!("Failed to read {}", legacy_profiles_json.display()))?;
        let value = serde_json::from_str::<serde_json::Value>(&raw)
            .with_context(|| format!("Failed to parse {}", legacy_profiles_json.display()))?;
        let executor_profiles = profiles_json_to_executor_profiles_yaml(value, &mut secrets)?;
        fragment.insert(
            serde_yaml::Value::String("executor_profiles".to_string()),
            executor_profiles,
        );
    } else {
        eprintln!(
            "warning: legacy profiles.json not found at {}, skipping",
            legacy_profiles_json.display()
        );
    }

    let fragment_yaml = serde_yaml::to_string(&serde_yaml::Value::Mapping(fragment.clone()))
        .context("Failed to serialize export as YAML")?;

    let validation_secret_env = if secrets.is_empty() {
        None
    } else {
        Some(secret_env_to_string(
            "vk migrate export-asset-config-yaml",
            &secrets,
        ))
    };
    validate_yaml_with_secret_env(&fragment_yaml, validation_secret_env.as_deref())?;

    let config_file_contents =
        build_config_yaml_file(&fragment_yaml, "vk migrate export-asset-config-yaml");

    if args.install {
        let slug = timestamp_slug();
        let config_out_path = config_dir.join(format!("config.migrated.{slug}.yaml"));
        let secret_out_path = config_dir.join(format!("secret.env.migrated.{slug}"));

        if args.dry_run {
            println!(
                "dry-run: would write migrated config YAML to {}",
                config_out_path.display()
            );
            if !secrets.is_empty() {
                println!(
                    "dry-run: would write migrated secret.env to {}",
                    secret_out_path.display()
                );
            }
            return Ok(());
        }

        atomic_write_out(&config_out_path, &config_file_contents)?;
        println!(
            "Wrote migrated config YAML to {}",
            config_out_path.display()
        );

        if !secrets.is_empty() {
            let secret_contents =
                secret_env_to_string("vk migrate export-asset-config-yaml", &secrets);
            atomic_write_out_secure(&secret_out_path, &secret_contents)?;
            println!("Wrote migrated secret.env to {}", secret_out_path.display());
        }

        eprintln!("next: merge into config.yaml + secret.env, then reload.");
        return Ok(());
    }

    let out_path = args.out.expect("checked above");
    if out_path.as_os_str() == "-" {
        print!("{config_file_contents}");
        if !secrets.is_empty() {
            eprintln!(
                "note: export references secret keys; run with --install to write secret.env.migrated.<timestamp>: {}",
                secrets.keys().cloned().collect::<Vec<_>>().join(", ")
            );
        }
        return Ok(());
    }

    if args.dry_run {
        println!("dry-run: would write export to {}", out_path.display());
        return Ok(());
    }

    atomic_write_out(&out_path, &config_file_contents)?;
    println!("Exported asset config YAML to {}", out_path.display());
    if !secrets.is_empty() {
        eprintln!(
            "note: export references secret keys; run with --install to write secret.env.migrated.<timestamp>"
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestEnvGuard {
        _lock: std::sync::MutexGuard<'static, ()>,
        prev_asset_dir: Option<String>,
        config_dir: PathBuf,
    }

    impl TestEnvGuard {
        fn new(temp_root: &std::path::Path) -> Self {
            let lock = super::super::test_lock()
                .lock()
                .unwrap_or_else(|err| err.into_inner());
            let prev_asset_dir = std::env::var("VIBE_ASSET_DIR").ok();

            let config_dir = temp_root.join("vk-config");
            std::fs::create_dir_all(&config_dir).unwrap();

            // SAFETY: tests using TestEnvGuard are serialized by test_lock.
            unsafe {
                std::env::set_var("VIBE_ASSET_DIR", temp_root);
            }

            Self {
                _lock: lock,
                prev_asset_dir,
                config_dir,
            }
        }
    }

    impl Drop for TestEnvGuard {
        fn drop(&mut self) {
            // SAFETY: tests using TestEnvGuard are serialized by test_lock.
            unsafe {
                match &self.prev_asset_dir {
                    Some(value) => std::env::set_var("VIBE_ASSET_DIR", value),
                    None => std::env::remove_var("VIBE_ASSET_DIR"),
                }
            }
        }
    }

    #[tokio::test]
    async fn install_writes_migrated_files_without_overwriting_config_yaml_or_secret_env() {
        let temp_root =
            std::env::temp_dir().join(format!("vk-asset-install-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&temp_root).unwrap();
        let _env_guard = TestEnvGuard::new(&temp_root);

        let asset_dir = utils_assets::asset_dir();
        let config_dir = &_env_guard.config_dir;

        let legacy_config_json = asset_dir.join("config.json");
        std::fs::write(
            &legacy_config_json,
            r#"{
  "github": { "pat": "ghp_test_123" }
}
"#,
        )
        .unwrap();

        let legacy_profiles_json = asset_dir.join("profiles.json");
        std::fs::write(
            &legacy_profiles_json,
            r#"{
  "executors": {
    "CODEX": {
      "DEFAULT": {
        "CODEX": {
          "env": { "OPENAI_API_KEY": "sk-test-123" }
        }
      }
    }
  }
}
"#,
        )
        .unwrap();

        run_export_asset_config_yaml(ExportAssetConfigYamlArgs {
            install: true,
            out: None,
            dry_run: false,
            print_paths: false,
            config_dir_override: Some(_env_guard.config_dir.clone()),
        })
        .await
        .expect("run export-asset-config-yaml --install");

        assert!(!config_dir.join("config.yaml").exists());
        assert!(!config_dir.join("secret.env").exists());

        let migrated_config = std::fs::read_dir(config_dir)
            .unwrap()
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .find(|path| {
                path.file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| {
                        name.starts_with("config.migrated.") && name.ends_with(".yaml")
                    })
            })
            .expect("migrated config file");

        let migrated_secret = std::fs::read_dir(config_dir)
            .unwrap()
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .find(|path| {
                path.file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.starts_with("secret.env.migrated."))
            })
            .expect("migrated secret file");

        let raw = std::fs::read_to_string(&migrated_config).expect("read migrated config");
        assert!(raw.contains("yaml-language-server"));
        assert!(raw.contains("{{secret.GITHUB_PAT}}"));
        assert!(raw.contains("{{secret.OPENAI_API_KEY}}"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&migrated_secret)
                .unwrap()
                .permissions()
                .mode()
                & 0o777;
            assert_eq!(mode, 0o600);
        }
    }
}
